pipeline:
  unittest:
    image: docker:1.12.1-dind
    privileged: true
    pull: true
    commands:
      - docker daemon -g /var/lib/docker &
      - docker run -v /go/src/github.com/CiscoCloud/vaquero-examples:/vaquero/local shippedrepos-docker-vaquero.bintray.io/vaquero/vaquero:latest validate —sot /vaquero/local
